name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go: ['1.16.x', '1.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        make build
    - name: Test
      run: |
        make test
